# -*- mode: tcl; coding: utf-8; indent-tabs-mode: nil; -*-

json_must_reject_file /dev/null
json_must_accept_file $srcdir/testsuite/json.test/test1.json

json_must_reject {}
json_must_reject " \n\r\t "
json_must_reject "\" \n\r\t \""
json_must_accept {{"key": "value", "stuff": ["this", "and", "that"]}}
json_must_accept {{"Shiba Inu": "柴犬"}}
json_must_accept {["\u003a", "\u00a3", "\u2207"]}
json_must_accept null
json_must_accept false
json_must_accept true
json_must_accept 123
json_must_accept 123.456
json_must_accept 123.456E7
json_must_accept 123.456E+7
json_must_accept 123.456E-7
json_must_accept {""}
json_must_accept {"Fnord!"}
json_must_accept {[]}
json_must_accept "{}"
json_must_accept {[null, false, true, 123, "Fnord!", {}, []]}
json_must_accept {{"object": [null, false, true, 123, "Fnord!", {}, []]}}
json_must_reject +123
json_must_reject 123.
json_must_reject "\"\u0000\""
json_must_reject "\"\u0001\""
json_must_reject "\"\u0002\""
json_must_reject "\"\u0003\""
json_must_reject "\"\u0004\""
json_must_reject "\"\u0005\""
json_must_reject "\"\u0006\""
json_must_reject "\"\u0007\""
json_must_reject "\"\u0008\""
json_must_reject "\"\u0009\""
json_must_reject "\"\u000A\""
json_must_reject "\"\u000B\""
json_must_reject "\"\u000C\""
json_must_reject "\"\u000D\""
json_must_reject "\"\u000E\""
json_must_reject "\"\u000F\""
json_must_reject "\"\u0010\""
json_must_reject "\"\u0011\""
json_must_reject "\"\u0012\""
json_must_reject "\"\u0013\""
json_must_reject "\"\u0014\""
json_must_reject "\"\u0015\""
json_must_reject "\"\u0016\""
json_must_reject "\"\u0017\""
json_must_reject "\"\u0018\""
json_must_reject "\"\u0019\""
json_must_reject "\"\u001A\""
json_must_reject "\"\u001B\""
json_must_reject "\"\u001C\""
json_must_reject "\"\u001D\""
json_must_reject "\"\u001E\""
json_must_reject "\"\u001F\""
json_must_reject "\"\u0022\""
json_must_reject "\"\u005C\""
json_must_reject "]"
json_must_reject "}"
json_must_reject "\["
json_must_reject "\{"
json_must_reject "\"\\\""
json_must_reject {""123}
